# service/exception_message.py


locale_not_exist = 'You haven\'t added any locale, but executing \'init_locales\''
